
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo Build / FirstJob
      - bash: echo $(PipeLineLevelVariable)
      
    - job: SecondJob
      steps:
      - bash: echo Build / SecondJob

  - stage: DevDeploy
    dependsOn: Build
    variables:
      environment: DevDeploy
    jobs:
    - job: FirstJob
      steps:
      - bash: echo $(environment) / FirstJob


  - stage: QADeploy
    dependsOn: Build
    variables:
      environment: QADeploy
    jobs:
    - job: FirstJob
      steps:
      - bash: echo $(environment) / FirstJob


  - stage: ProdDeploy
    dependsOn:
    - Devdeploy
    - QADeploy
    variables:
      environment: QADeploy
    jobs:
    - job: FirstJob
      steps:
      - bash: echo $(environment) / FirstJob
