trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'


- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@2
  displayName: 'terraform init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmSubscriptionId: '8b67cfd8-9c7e-4151-96b4-f09f5ca453b4'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'uksouth'
    backendAzureRmStorageAccountName: 'storegeaccountbob'
    backendAzureRmContainerName: 'storageaccountbobcontainer'
    backendAzureRmKey: 'kubernetes-dev-tfstate'
    allowTelemetryCollection: true


- task: TerraformCLI@2
  displayName: 'terraform apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resource-manager-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    allowTelemetryCollection: true
